### ISSUE TITLE
Essentielle Mailingliste `info-announce` fehlt in der Aufzählung

### ISSUE THREAD

**Issue by fkellner** [fsi-tue/cyberauftritt#101]
In den Infos für Studierende wird bei den Mailinglisten `info-studium` als essentiell wichtig beworben. Nicht erwähnt wird `info-announce`, über das dieses Semester essentielle Einladungen zu Ersti-Veranstaltungen verschickt wurden (und generelle Studieninfos). Bitte nehmt `info-announce` noch in die essentiellen Mailinglisten mit auf!

**Comment by PhictionalOne** [comment]
`info-announce` ist `info-studium`, nur dass der  `[info-announce] `-Tag signalisiert, dass die Mail von einem Prof. kam.

**Comment by primeos** [comment]
Hab mal #102 als Entwurf zur Dokumentation erstellt.
