### ISSUE TITLE
Update Anfi* -  Seite

### ISSUE THREAD

**Issue by PhictionalOne** [fsi-tue/cyberauftritt#112]
its time to update [`anfiveranstaltungen.tex`](https://github.com/fsi-tue/cyberauftritt/blob/master/anfiveranstaltungen.md) or at least to have it on the radar

**Comment by luoe** [comment]
WIP. Thanks!

**Comment by luoe** [comment]
See c9836f175bcd0ead53e17022c1db389a5fa9f1f5 for first changes

**Comment by PhictionalOne** [comment]
> WIP. Thanks!
> See [c9836f1](https://github.com/fsi-tue/cyberauftritt/commit/c9836f175bcd0ead53e17022c1db389a5fa9f1f5) for first changes

Nice!

**Comment by luoe** [comment]
The rest will be done via the calendar.
