### ISSUE TITLE
Rewrite Corona Pages

### ISSUE THREAD

**Issue by PhictionalOne** [fsi-tue/cyberauftritt#113]
As the situation is not identical to last semester I propose to...
- ... rewrite the [Corona FAQ](https://github.com/fsi-tue/cyberauftritt/blob/master/covid19/faq.md) and to ...
- ... remove the [Corona Vorlesungen](https://github.com/fsi-tue/cyberauftritt/blob/master/covid19/vorlesungen.md) page 
The intent of last semester to help old students in the move from Campus to Alma should be resolved now. 
And we don't have a spreadsheet to parse.

As for helping new students. The big lectures *Info 1, Mathe 1* and other introductory courses like ie. *ETI* can be put into the FAQ again.

If I missed something please append!

**Comment by luoe** [comment]
Sounds great! Please open a PR with ongoing changes

**Comment by luoe** [comment]
@PhictionalOne You are very welcome to use WIP Pull Requests :smile: 

https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by PhictionalOne** [comment]
See #114

**Comment by luoe** [comment]
Thanks! Please do not close this issue, track further changes (i.e. Mathe I and ETI)

**Comment by luoe** [comment]
Is this still relevant? We could convert this into a "meta-issue" for the upcoming semesters. Or make a new one....

**Comment by PhictionalOne** [comment]
> Is this still relevant? We could convert this into a "meta-issue" for the upcoming semesters. Or make a new one.... 
@luoe 

A meta issue sounds fine

**Comment by luoe** [comment]
Closing in favor of #123
