### ISSUE TITLE
Table of contens for longer pages

### ISSUE THREAD

**Issue by PhictionalOne** [fsi-tue/cyberauftritt#41]
Sidebar left with [jekyll-toc](https://github.com/toshimaru/jekyll-toc) for pages with much content

In mobile view above content (Bootstrap shit)

**Comment by luoe** [comment]
Do we still need this?

**Comment by ST0PPELB4RT** [comment]
would be nice to scan for a special topic. On the other hand people should be able to use `STRG + F` (at least on PCs)

**Comment by luoe** [comment]
@PhictionalOne

**Comment by luoe** [comment]
Fixed in bd5a8448c50a3c74dce34ef576ffe967a7ce8cd6.
Thanks again, @PhictionalOne!
