### ISSUE TITLE
Add an appropiate startpage

### ISSUE THREAD

**Issue by luoe** [fsi-tue/cyberauftritt#42]
Currently, the startpage /homepage includes only some text and links from the standard template. There should be a greeting, some lines about first things first and links to the most relevant subpages (i.e. mailing lists, lecture notes etc.)

**Comment by elogy** [comment]
I'd suggest the following structure, but at the moment I don't have the time to write the stuff down (maybe on sunday):

```
# Startseite

## Für Studieninteressierte

## Für Erstsemester
### FAQ

### Veranstaltungen

### Material

## Für höhere Semester 
### FAQ

### Studienpläne

### Formulare und Prüfungsanmeldung

### Studienberatung

## Mitmachen?

```
