### ISSUE TITLE
GitHub Pages build failes after integrating #48

### ISSUE THREAD

**Issue by luoe** [fsi-tue/cyberauftritt#50]
After merging #48 (commit 54fd32e90a07d6f9540822ae11a69281cf16c145), GitHub pages doesn't build the site anymore:
> Your site is having problems building: The tag ical on line 14 in _includes/sidebar.html is not a recognized Liquid tag. For more information, see https://help.github.com/en/articles/page-build-failed-unknown-tag-error.

Building (and running with Docker) works locally.

**Comment by luoe** [comment]
See also https://travis-ci.org/fsi-tue/cyberauftritt/builds/571931599

**Comment by primeos** [comment]
It should work again after we move the deployment to our own infrastructure.
Unfortunately GitHub doesn't support custom plugins (was too late to comment on #48), only those listed [here](https://help.github.com/en/articles/configuring-jekyll-plugins) or [here](https://pages.github.com/versions/).

https://jekyllrb.com/docs/plugins/installation/:
> # Plugins on GitHub Pages
> GitHub Pages is powered by Jekyll. All Pages sites are generated using the --safe option to disable plugins (with the exception of some whitelisted plugins) for security reasons. Unfortunately, this means your plugins won’t work if you’re deploying to GitHub Pages.

There is a workaround:
> You can still use GitHub Pages to publish your site, but you’ll need to convert the site locally and push the generated static files to your GitHub repository instead of the Jekyll source files.

But we should avoid it as it would only bloat this repository and will not be updated automatically.

**Comment by luoe** [comment]
Yeah, we could create the gh-pages branch, build locally and push, but this would be really ineffective.
When moving to our infrastructure, we could automatically make subdirectories for branches (like for users on teri), i.e. replacing GitHub Pages with our infrastructure.

**Comment by luoe** [comment]
For now, I created the gh-pages branch and removed changes made in #48, so that GitHub Pages will be able to build the new site, showing at least the new content. When we deploy the website on our infrastructure, we can remove the gh-pages branch again and disable GitHub Pages.
Closing for now.

**Comment by primeos** [comment]
@luoe but why create an additional `gh-pages` branch?

IMO this makes it more confusing as we have two branches now. I would simply revert the changes from #48 in `master` and merge them again after we deploy the website on our own infrastructure.
