### ISSUE TITLE
Why do we use two branches?

### ISSUE THREAD

**Issue by primeos** [fsi-tue/cyberauftritt#56]
Currently we have the `master` and `gh-pages` branches while `gh-pages` has only tree additional commits:

```
commit f3aa1e0b5dbe30a9beea9b7ee775f01f40631214 (origin/gh-pages)
Author: Lukas Oertel <git@luoe.dev>
Date:   Sun Aug 25 19:11:54 2019 +0200

    Make table for Studienberatung responsive

commit 951c8c068c8ffd227f0438de3667e4d3d16ff170
Author: Tim Beckmann <tim.beckmann@student.uni-tuebingen.de>
Date:   Sun Aug 25 18:59:13 2019 +0200

    fix h1 headings for mobile views (300-768px) (#55)

commit 92310dd46bd41d5a5d770388cbb3812920d0df65
Merge: 2bb882a b2f8af3
Author: Lukas Oertel <git@luoe.dev>
Date:   Sun Aug 25 18:18:53 2019 +0200

    Merge pull request #54 from fsi-tue/master
    
    Update gh-pages branch

commit b2f8af34ec01470b9f8397a6eb723e2889ad9742 (origin/master, origin/HEAD)
Author: Lukas Oertel <git@luoe.dev>
Date:   Sun Aug 25 18:14:42 2019 +0200

    Fix css/main.css
    
    Fixes #53
```

This is not documented and seems to unnecessarily complicate things. IMO an extra `gh-pages` branch is mainly useful it the repository is used for code (some software) and documentation (website).

Therefore my question, if we need the additional `gh-pages` branch, does still apply: https://github.com/fsi-tue/cyberauftritt/issues/50#issuecomment-522326884

**Comment by luoe** [comment]
As we have deployed the website to our infrastructure, we don't need Github Pages anymore. I delete the gh-pages branch and also disable Github Pages for this repo.
